# Generated by Django 3.2.9 on 2023-06-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('registered', models.DateTimeField()),
                ('usage', models.IntegerField()),
                ('period', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('serviceState', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.plan')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='Framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.framework'),
        ),
        migrations.AddField(
            model_name='domain',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.profile'),
        ),
    ]
