# Generated by Django 3.2.9 on 2023-06-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='servicestatus',
            name='Service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.service'),
        ),
    ]
