# Generated by Django 3.2.9 on 2023-06-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0004_auto_20230601_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestatus',
            name='name',
        ),
    ]
