# Generated by Django 3.2.9 on 2023-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_remove_servicestatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
