# Generated by Django 3.2.9 on 2023-06-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0008_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=3)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField()),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.plan')),
                ('Service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.service')),
            ],
        ),
    ]
