# Generated by Django 3.2.9 on 2023-07-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0011_auto_20230705_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
