# Generated by Django 3.2.9 on 2023-07-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0012_auto_20230705_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='label',
        ),
        migrations.AddField(
            model_name='service',
            name='Area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.area'),
        ),
    ]
