# Generated by Django 3.2.9 on 2023-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0013_auto_20230705_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
