# Generated by Django 3.2.9 on 2023-07-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0015_frameworkxservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='price',
        ),
        migrations.CreateModel(
            name='PlanXService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.plan')),
                ('Service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.service')),
            ],
        ),
    ]
