# Generated by Django 3.2.9 on 2023-07-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0017_planxservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='planxservice',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
