# Generated by Django 3.2.9 on 2023-07-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0018_planxservice_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField()),
                ('PlanXService', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.planxservice')),
                ('Profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.profile')),
            ],
        ),
    ]
