# Generated by Django 3.2.9 on 2023-07-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0019_profileservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Plan',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
