# Generated by Django 3.2.9 on 2023-07-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0021_auto_20230706_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='Service',
        ),
        migrations.AddField(
            model_name='consumption',
            name='ProfileServices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.profileservices'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commons.domain'),
        ),
    ]
