# Generated by Django 3.2.9 on 2023-07-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0022_auto_20230706_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
