# Generated by Django 3.2.9 on 2023-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0027_conceptobserver_concept_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptobserver',
            name='concept_properties',
            field=models.CharField(default='', max_length=300),
        ),
    ]
